# permissions for end users to view pangolinbindings.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: pangolin-operator
    app.kubernetes.io/managed-by: kustomize
  name: pangolinbinding-viewer-role
rules:
- apiGroups:
  - tunnel.pangolin.io
  resources:
  - pangolinbindings
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - tunnel.pangolin.io
  resources:
  - pangolinbindings/status
  verbs:
  - get
