## Append samples of your project ##
resources:
- tunnel_v1alpha1_pangolintunnel.yaml
- tunnel_v1alpha1_pangolinresource.yaml
- tunnel_v1alpha1_pangolinbinding.yaml
# +kubebuilder:scaffold:manifestskustomizesamples
