apiVersion: tunnel.pangolin.io/v1alpha1
kind: PangolinBinding
metadata:
  labels:
    app.kubernetes.io/name: pangolin-operator
    app.kubernetes.io/managed-by: kustomize
  name: pangolinbinding-sample
spec:
  # TODO(user): Add fields here
